table QUOTE
	isHidden
	lineageTag: e1d3e702-5d61-4d2f-ae90-4d909c9aab9c

	column 'Quote ID'
		dataType: string
		isHidden
		lineageTag: d0a8ebec-a015-4370-ad5d-7e155296132f
		summarizeBy: none
		sourceColumn: Quote ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Opportunity ID'
		dataType: string
		isHidden
		lineageTag: 659dc661-b3db-4bc6-addb-0632208ed5fe
		summarizeBy: none
		sourceColumn: Opportunity ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		isHidden
		lineageTag: b008ff81-864d-4c43-a7af-f78b15dea246
		summarizeBy: none
		sourceColumn: Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		isHidden
		lineageTag: 6099256e-6fd2-40fd-8ff8-5a630b547476
		summarizeBy: none
		sourceColumn: Customer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Agent ID'
		dataType: string
		isHidden
		lineageTag: 313c1086-5f2c-4e7e-bc46-cae93df2602b
		summarizeBy: none
		sourceColumn: Agent ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'End User ID'
		dataType: string
		isHidden
		lineageTag: fad7564e-a11b-42e1-a2f2-7334216ea89f
		summarizeBy: none
		sourceColumn: End User ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		isHidden
		lineageTag: 3e701500-676e-4e90-aa96-19c30d09def6
		summarizeBy: none
		sourceColumn: Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Expected Delivery Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 53135be9-92b5-47ae-b7d0-e7dcb2c8b3cc
		summarizeBy: none
		sourceColumn: Expected Delivery Date

		variation Variation
			isDefault
			relationship: 4b0f9f9d-d2f8-40b3-9baf-344baed344cf
			defaultHierarchy: LocalDateTable_b56ce335-2536-4575-8d4f-7b605014f6e4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Last Modified Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 137d0467-c877-4a42-b790-f6a40df2b344
		summarizeBy: none
		sourceColumn: Last Modified Date

		variation Variation
			isDefault
			relationship: 364c4879-9e1c-4775-a86c-ac176c425444
			defaultHierarchy: LocalDateTable_07c9221f-8244-4ed2-a76c-e04af265032d.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Valid From Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 2ad5fbd6-ff68-464f-9822-9584bffd59fa
		summarizeBy: none
		sourceColumn: Valid From Date

		variation Variation
			isDefault
			relationship: ea939036-1b5e-4e03-82c5-c356762fb2c1
			defaultHierarchy: LocalDateTable_f4cd4a3c-142e-422b-8fd3-f71ae456203e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Validity Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 6d877ac4-5448-449e-9b2a-98549100c483
		summarizeBy: none
		sourceColumn: Validity Date

		variation Variation
			isDefault
			relationship: b7a1be0f-321a-4ba5-b816-524762aa352f
			defaultHierarchy: LocalDateTable_7346b757-508a-4fee-a137-3859ebdf92f2.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Incoterms
		dataType: string
		isHidden
		lineageTag: c39cac9d-9fee-4035-9864-bb9305622393
		summarizeBy: none
		sourceColumn: Incoterms

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Probability
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a339f5b8-0425-4de8-a1c6-c8c15edb0fd7
		summarizeBy: sum
		sourceColumn: Probability

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SFDC Quote ID'
		dataType: string
		isHidden
		lineageTag: 3c17f25c-b203-4905-931e-19843ebc3570
		summarizeBy: none
		sourceColumn: SFDC Quote ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'S Number'
		dataType: string
		isHidden
		lineageTag: a29c1683-e290-419e-9cf7-7ce797c423ac
		summarizeBy: none
		sourceColumn: S Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Created Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 0b171c4a-4746-4d82-a533-94ac59f5933e
		summarizeBy: none
		sourceColumn: Created Date

		variation Variation
			isDefault
			relationship: 1b50a952-ceb3-4a69-9695-320ef8df5f3b
			defaultHierarchy: LocalDateTable_1f701ee2-5b16-4938-a209-9082cc332c10.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition QUOTE = m
		mode: import
		queryGroup: Salesforce
		source =
				let
				    Source = Odbc.DataSource(dsn, [HierarchicalNavigation=true]),
				    INS_Schema = Source{[Name="INS",Kind="Schema"]}[Data],
				    Z_INS_SFDC_Quote_F_V_View = INS_Schema{[Name="Z_INS_SFDC_Quote_F_V",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Z_INS_SFDC_Quote_F_V_View,{{"LastModifiedDate", type date}, {"Quote_valid_from__c", type date}, {"Quote_validity__c", type date}, {"CreatedDate", type date}, {"Probability__c", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"AccountId", "Agent__c", "End_User__c", "Expected_Delivery_Date__c", "Id", "Incoterms_Part_1__c", "LastModifiedDate", "Name", "OpportunityId", "Probability__c", "Quotation_No__c", "Quote_valid_from__c", "Quote_validity__c", "S_number__c", "Status", "CreatedDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"AccountId", "Customer ID"}, {"Agent__c", "Agent ID"}, {"End_User__c", "End User ID"}, {"Expected_Delivery_Date__c", "Expected Delivery Date"}, {"Id", "Quote ID"}, {"Incoterms_Part_1__c", "Incoterms"}, {"LastModifiedDate", "Last Modified Date"}, {"OpportunityId", "Opportunity ID"}, {"Probability__c", "Probability"}, {"Quotation_No__c", "SFDC Quote ID"}, {"Quote_valid_from__c", "Valid From Date"}, {"Quote_validity__c", "Validity Date"}, {"S_number__c", "S Number"}, {"CreatedDate", "Created Date"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Quote ID", "Name", "Customer ID", "Agent ID", "End User ID", "Status", "Expected Delivery Date", "Last Modified Date", "Valid From Date", "Validity Date", "Incoterms", "Opportunity ID", "Probability", "SFDC Quote ID", "S Number", "Created Date"})
				in
				    #"Reordered Columns"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

