table Sales
	lineageTag: 8c6b0ea3-d68d-4e0f-8aba-9f1dfb3dead9

	column CATEGORY
		dataType: string
		lineageTag: 365e2dba-0399-43c7-97f0-3560229e6508
		summarizeBy: none
		sourceColumn: CATEGORY

		annotation SummarizationSetBy = Automatic

	column SUB-CATEGORY
		dataType: string
		lineageTag: 2c4764b1-116e-4faa-9927-e99865368f4a
		summarizeBy: none
		sourceColumn: SUB-CATEGORY

		annotation SummarizationSetBy = Automatic

	column SALES
		dataType: int64
		formatString: 0
		lineageTag: d702fc98-73a3-42d9-a32f-e2a782c5b630
		summarizeBy: sum
		sourceColumn: SALES

		annotation SummarizationSetBy = Automatic

	column PROFIT
		dataType: int64
		formatString: 0
		lineageTag: aef25775-8593-4e13-8c99-517f2f666651
		summarizeBy: sum
		sourceColumn: PROFIT

		annotation SummarizationSetBy = Automatic

	column QTY
		dataType: int64
		formatString: 0
		lineageTag: 94996b71-a0af-415a-bc58-3a69dec5c8a0
		summarizeBy: sum
		sourceColumn: QTY

		annotation SummarizationSetBy = Automatic

	column Product_Key
		dataType: int64
		formatString: 0
		lineageTag: d9654708-14ad-4e03-8e5d-af72e961a545
		summarizeBy: count
		sourceColumn: Product_Key

		annotation SummarizationSetBy = Automatic

	column Location_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 45ef0213-6e4b-4656-9739-c5ccbcb4eda0
		summarizeBy: count
		sourceColumn: Location_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country_Key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8ce7314a-15e7-4251-b98b-bc99adf8cafb
		summarizeBy: count
		sourceColumn: Country_Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZLPDoIwDIdfxXDmAMj4c6zLgEVclw0Ohvj+r+HWmghRkQOlDXz5fSssS9LNzuhpdipJufeDNr0PU55lWbgVVPMiljiG65w80i15QbxK8MozEImSabHLTXAZCTozJKhW+5AcQDvPEfT6ryTsOi3Vyc/Wjppi/IQOesVJkarZNT/AQuzASBpKNm3YujqAW7DKxefipUvxzRHpd1us4S9rmpQcDI7Y32PigGYt+2LLfQpkOKFHx4GVWK1YfNpuUIlWK/oyNWM1eZZ/PG8gwz9HcS1zbUPLrbfc4wk=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CATEGORY = _t, #"SUB-CATEGORY" = _t, SALES = _t, PROFIT = _t, QTY = _t, Product_Key = _t, Location_Key = _t, Country_Key = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"CATEGORY", type text}, {"SUB-CATEGORY", type text}, {"SALES", Int64.Type}, {"PROFIT", Int64.Type}, {"QTY", Int64.Type}, {"Product_Key", Int64.Type}, {"Location_Key", Int64.Type}, {"Country_Key", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

